In [58]:
#In this notebook we try to practice all the classification algorithms that we learned in this course.

#We load a dataset using Pandas library, and apply the following algorithms, and find the best one for this specific dataset by accuracy evaluation methods.

#Lets first load required libraries:


import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline

In [59]:

#Load Data From CSV File
#Let's load the dataset [NB Need to provide link to csv file]


df = pd.read_excel('path_to_file\VENDIDOS1MESHISTORICOml2.xlsx')

df.head()


MARCA MODELO  MOTOR  CAMBIO   CV COMBUSTIBLE COLOR   PROVEEDOR  YEARS  \
0     RENAULT MEGANE    1.6  MANUAL   75    GASOLINA   NaN     G.COSTA     10   
1          VOLVO S60    2.5  MANUAL  145    GASOLINA   NaN  PARTICULAR      7   
2  VOLKSWAGEN PASSAT    1.9  MANUAL  130      DIESEL   NaN   LEASEPLAN      5   
3        SEAT TOLEDO    1.9  MANUAL  110      DIESEL   NaN   LEASEPLAN      5   
4      SKODA OCTAVIA    1.9  MANUAL  105      DIESEL   NaN   LEASEPLAN      3   

   PLAZAS      PCC  ...  edad  mes  year  CTE.GARANTÍA  CTE..PREPARACIÓN  \
0     NaN    956.6  ...   NaN    1  2008           NaN               NaN   
1     NaN   7900.0  ...   NaN    2  2008           NaN               NaN   
2     NaN  11200.0  ...   NaN    2  2008           NaN               NaN   
3     NaN   7300.0  ...   NaN    3  2008           NaN               NaN   
4     NaN  10000.0  ...   NaN    3  2008           NaN               NaN   

   CTE.TOTAL BF.NETO GARANTIA  MESES GARANTIA2  
0        NaN     NaN      NaN    NaN       NaN  
1        NaN     NaN      NaN    NaN       NaN  
2        NaN     NaN      NaN    NaN       NaN  
3        NaN     NaN      NaN    NaN       NaN  
4        NaN     NaN      NaN    NaN       NaN  

[5 rows x 34 columns]

In [60]:

df.shape

(381, 34)

In [61]:
# We wan to know of total GARANTIA 2 which are good or MESES with value to 1
df[(df.GARANTIA==2) & (df.MESES==1.0)].shape

(16, 34)

In [62]:
df3=df[(df.GARANTIA==2)]
df3.shape


(31, 34)

In [64]:
Accuracygarangtia2=16/34


Accuracygarangtia2

0.47058823529411764

In [65]:

#Use one hot encoding technique to conver categorical varables to binary variables and append them to the feature Data Frame
df.drop(['GARANTIA','BF.NETO','CTE.TOTAL','CTE.GARANTÍA','edad','sexo','nacionalidad','pais','provincia','localidad','C.P','C AUTO1','NETO','mes'], axis = 'columns', inplace=True)


In [66]:
#Feature after One Hot Encoding
df.head()

MARCA MODELO  MOTOR  CAMBIO   CV COMBUSTIBLE COLOR   PROVEEDOR  YEARS  \
0     RENAULT MEGANE    1.6  MANUAL   75    GASOLINA   NaN     G.COSTA     10   
1          VOLVO S60    2.5  MANUAL  145    GASOLINA   NaN  PARTICULAR      7   
2  VOLKSWAGEN PASSAT    1.9  MANUAL  130      DIESEL   NaN   LEASEPLAN      5   
3        SEAT TOLEDO    1.9  MANUAL  110      DIESEL   NaN   LEASEPLAN      5   
4      SKODA OCTAVIA    1.9  MANUAL  105      DIESEL   NaN   LEASEPLAN      3   

   PLAZAS      PCC  PCOMPRA  PVENTA   BRUTO      KM tipo llantas  year  \
0     NaN    956.6    956.6    4500  3543.4  109988  med      si  2008   
1     NaN   7900.0   7900.0   10500  2600.0  185390  gra      si  2008   
2     NaN  11200.0  11200.0   15750  4550.0   73790  gra      si  2008   
3     NaN   7300.0   7300.0    9900  2600.0   97257  gra      si  2008   
4     NaN  10000.0  10000.0   12600  2600.0   92481  gra      si  2008   

   CTE..PREPARACIÓN  MESES GARANTIA2  
0               NaN    NaN       NaN  
1               NaN    NaN       NaN  
2               NaN    NaN       NaN  
3               NaN    NaN       NaN  
4               NaN    NaN       NaN

In [67]:
df = df.dropna()
df.head()

MARCA MODELO  MOTOR  CAMBIO   CV COMBUSTIBLE   COLOR   PROVEEDOR  \
99   VOLKSWAGEN POLO    1.4  MANUAL   75    GASOLINA   NEGRO      MAVISA   
100    OPEL INSIGNIA    2.0  MANUAL  130      DIESEL  BLANCO       ARVAL   
101       CITROEN C4    1.6  MANUAL  110    GASOLINA    GRIS       AUTO1   
102          AUDI A4    1.9  MANUAL  130      DIESEL   PLATA  MUNDOMOVIL   
103   RENAULT TRAFIC    2.0  MANUAL  115      DIESEL  BLANCO       ARVAL   

     YEARS  PLAZAS      PCC  PCOMPRA  PVENTA   BRUTO      KM tipo llantas  \
99      12     5.0   1805.0   1805.0    4500  2695.0   91431  peq      si   
100      4     5.0  10821.0  10821.0   13300  2479.0   74210  gra      si   
101     10     5.0   2250.0   2250.0    5300  3050.0   82294  med      no   
102     12     5.0   4000.0   4000.0    7500  3500.0  184488  gra      si   
103      6     6.0  10900.0  10900.0   13700  2800.0   84172  fur      no   

     year  CTE..PREPARACIÓN  MESES GARANTIA2  
99   2016           2089.46    2.0        si  
100  2016            307.60    1.0        si  
101  2016            986.07    1.0        si  
102  2016            967.89    1.0        si  
103  2016            821.60    1.0        si

In [68]:
df.isnull().sum()

MARCA MODELO        0
MOTOR               0
CAMBIO              0
CV                  0
COMBUSTIBLE         0
COLOR               0
PROVEEDOR           0
YEARS               0
PLAZAS              0
PCC                 0
PCOMPRA             0
PVENTA              0
BRUTO               0
KM                  0
tipo                0
llantas             0
year                0
CTE..PREPARACIÓN    0
MESES               0
GARANTIA2           0
dtype: int64

In [69]:
df = pd.DataFrame(df)

df_columns = df.columns

In [70]:
predictors = df[df_columns[df_columns != 'MESES']] # all columns except MESES 
target = df['MESES'] # MESES  column

In [71]:
predictors.head()

MARCA MODELO  MOTOR  CAMBIO   CV COMBUSTIBLE   COLOR   PROVEEDOR  \
99   VOLKSWAGEN POLO    1.4  MANUAL   75    GASOLINA   NEGRO      MAVISA   
100    OPEL INSIGNIA    2.0  MANUAL  130      DIESEL  BLANCO       ARVAL   
101       CITROEN C4    1.6  MANUAL  110    GASOLINA    GRIS       AUTO1   
102          AUDI A4    1.9  MANUAL  130      DIESEL   PLATA  MUNDOMOVIL   
103   RENAULT TRAFIC    2.0  MANUAL  115      DIESEL  BLANCO       ARVAL   

     YEARS  PLAZAS      PCC  PCOMPRA  PVENTA   BRUTO      KM tipo llantas  \
99      12     5.0   1805.0   1805.0    4500  2695.0   91431  peq      si   
100      4     5.0  10821.0  10821.0   13300  2479.0   74210  gra      si   
101     10     5.0   2250.0   2250.0    5300  3050.0   82294  med      no   
102     12     5.0   4000.0   4000.0    7500  3500.0  184488  gra      si   
103      6     6.0  10900.0  10900.0   13700  2800.0   84172  fur      no   

     year  CTE..PREPARACIÓN GARANTIA2  
99   2016           2089.46        si  
100  2016            307.60        si  
101  2016            986.07        si  
102  2016            967.89        si  
103  2016            821.60        si

In [72]:
target.head()

99     2.0
100    1.0
101    1.0
102    1.0
103    1.0
Name: MESES, dtype: float64

In [73]:
predictors = pd.get_dummies(predictors, columns = ["MARCA MODELO"])
predictors = pd.get_dummies(predictors, columns = ["CAMBIO"])
predictors = pd.get_dummies(predictors, columns = ["COMBUSTIBLE"])
predictors = pd.get_dummies(predictors, columns = ["COLOR"])
predictors = pd.get_dummies(predictors, columns = ["PROVEEDOR"])
predictors = pd.get_dummies(predictors, columns = ["tipo"])
predictors = pd.get_dummies(predictors, columns = ["llantas"])
predictors = pd.get_dummies(predictors, columns = ["GARANTIA2"])


In [74]:
#Feature selection
#Lets defind feature sets, X:


x = predictors

x[0:5]

MOTOR   CV  YEARS  PLAZAS      PCC  PCOMPRA  PVENTA   BRUTO      KM  \
99     1.4   75     12     5.0   1805.0   1805.0    4500  2695.0   91431   
100    2.0  130      4     5.0  10821.0  10821.0   13300  2479.0   74210   
101    1.6  110     10     5.0   2250.0   2250.0    5300  3050.0   82294   
102    1.9  130     12     5.0   4000.0   4000.0    7500  3500.0  184488   
103    2.0  115      6     6.0  10900.0  10900.0   13700  2800.0   84172   

     year  ...  tipo_mon  tipo_monp  tipo_peq  tipo_pickup  tipo_sub  tipo_tt  \
99   2016  ...         0          0         1            0         0        0   
100  2016  ...         0          0         0            0         0        0   
101  2016  ...         0          0         0            0         0        0   
102  2016  ...         0          0         0            0         0        0   
103  2016  ...         0          0         0            0         0        0   

     llantas_no  llantas_si  GARANTIA2_no  GARANTIA2_si  
99            0           1             0             1  
100           0           1             0             1  
101           1           0             0             1  
102           0           1             0             1  
103           1           0             0             1  

[5 rows x 144 columns]

In [75]:

#What are our lables?

y = target
y[0:5]

99     2.0
100    1.0
101    1.0
102    1.0
103    1.0
Name: MESES, dtype: float64

In [76]:
#use train/test split to start to model
#import libraries to use 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [77]:
#use train test splot to split into training 80% and 20% for testing, with a random state of 3
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=1, random_state=3)

In [78]:
#print shape of train and test shape to check if both are correct
print('train set: ',x_train.shape,y_train.shape)
print('test set: ',x_test.shape,y_test.shape)

train set:  (281, 144) (281,)
test set:  (1, 144) (1,)


In [79]:
#This model is going to predict the MESES type based on the car characteristics. This is categorized
#as a classification machine learning technique.Different models will be used to evaluate the prediction 
#accuracy.

In [80]:
#DECISION TREE MODEL
#First, create an instance of the decision tree clasifier,
treecomp= DecisionTreeClassifier(criterion="entropy", max_depth = 4)
treecomp

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=4, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [81]:
#fit the data with the training set
treecomp.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=4, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [82]:
x_test = pd.read_excel(r'C:\Users\djina\OneDrive\Documentos\Data Science\Becars\predictorsbruto.xlsx')

In [83]:
#make some predctions on the test dataset
predtree= treecomp.predict(x_test)
x_test.head()

MOTOR  CV  YEARS  PLAZAS   PCC  PCOMPRA  PVENTA  BRUTO      KM  year  ...  \
0      2  90     14       5  1500     1500    2900   1400  202069  2015  ...   

   tipo_mon  tipo_monp  tipo_peq  tipo_pickup  tipo_sub  tipo_tt  llantas_no  \
0         0          0         0            0         0        0           0   

   llantas_si  GARANTIA2_no  GARANTIA2_si  
0           1             1             0  

[1 rows x 144 columns]

In [84]:
#print the predction values and the y_test values to compare
print(predtree[0:5])


[2.]


In [99]:
#K-NEAREST METHOD

import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline


In [100]:
x = pd.read_excel(r'C:\Users\djina\OneDrive\Documentos\Data Science\Becars\predictors2bruto.xlsx')

In [101]:
x = preprocessing.StandardScaler().fit(x).transform(x.astype(float))

In [102]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( x, y, test_size=1, random_state=3)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (281, 144) (281,)
Test set: (1, 144) (1,)


In [103]:

#Classification
#K nearest neighbor (KNN)
#Import library
#Classifier implementing the k-nearest neighbors vote.

from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier




In [104]:
X_test[0:5]

array([[ 0.93805631, -0.78175056,  1.72140608, -0.26863248, -1.24157475,
        -1.16009238, -1.64065949, -1.50291339,  2.21982993, -1.07510436,
        -1.50313135, -0.17087153, -0.08451543, -0.10369517, -0.059655  ,
        -0.059655  , -0.10369517, -0.21081851, -0.10369517, -0.059655  ,
        -0.1343523 , -0.059655  , -0.08451543, -0.059655  , -0.059655  ,
        -0.059655  , -0.059655  , -0.08451543, -0.1343523 , -0.21983434,
        -0.059655  , -0.059655  , -0.059655  , -0.11995203, -0.059655  ,
        -0.059655  , -0.059655  , -0.08451543, -0.059655  , -0.059655  ,
        -0.08451543, -0.059655  , -0.059655  , -0.059655  , -0.11995203,
        -0.059655  , -0.15954481, -0.059655  , -0.31868872, -0.08451543,
        -0.11995203, -0.26111648, -0.18156826, -0.059655  , -0.10369517,
        -0.20147061, -0.08451543, -0.059655  , 16.76305461, -0.08451543,
        -0.059655  , -0.059655  , -0.059655  , -0.14744196, -0.059655  ,
        -0.08451543, -0.10369517, -0.10369517, -0.1

In [105]:
#Training
#Lets start the algorithm with k=3 for now:

k = 3
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [106]:
yhatk3 = neigh.predict(X_test)
yhatk3[0:5]

array([2.])

In [107]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhatk3))

Train set Accuracy:  0.7651245551601423
Test set Accuracy:  1.0


In [108]:
#Training
#Lets start the algorithm with k=7 for now:

k = 7
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [109]:
yhatk7 = neigh.predict(X_test)
yhatk7[0:5]

array([2.])

In [110]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhatk7))

Train set Accuracy:  0.7046263345195729
Test set Accuracy:  1.0


In [111]:
#Training
#Lets start the algorithm with k=15 for now:

k = 1
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [112]:
yhatk15 = neigh.predict(X_test)
yhatk15[0:5]

array([2.])

In [113]:
print(predtree[0:5],yhatk3[0:5],yhatk7[0:5],yhatk15[0:5])

[2.] [2.] [2.] [2.]
